# Generated by Django 4.1.5 on 2023-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_customuser_access_control_customuser_additional_info_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("zip_code", models.IntegerField()),
                ("federal_EIN", models.CharField(max_length=200)),
            ],
        ),
    ]
