# Generated by Django 4.2.7 on 2023-11-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_facility_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "Facilities"},
        ),
    ]
