# Generated by Django 4.2.7 on 2023-11-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_facility_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_pic",
            field=models.ImageField(
                blank=True, default=1, null=True, upload_to="images/"
            ),
        ),
    ]
