# Generated by Django 4.2.7 on 2023-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
