# Generated by Django 4.2.7 on 2023-11-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_control",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clinicians", "Clinicians"),
                    ("front office", "Front Office"),
                    ("physicians", "Physicians"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
