# Generated by Django 4.1.5 on 2023-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("dob", models.DateTimeField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "other"),
                        ],
                        max_length=200,
                    ),
                ),
                ("license_id", models.CharField(max_length=200)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("married", "Married"),
                            ("single", "Single"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separatd", "Separeted"),
                            ("domestic partner", "Domestic Partner"),
                        ],
                        help_text="optional",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(blank=True, max_length=500, null=True)),
                ("state", models.CharField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("postal_code", models.IntegerField()),
                ("emergency_phone", models.IntegerField(help_text="phone number?")),
                (
                    "home_phone",
                    models.IntegerField(
                        blank=True, help_text="phone number?", null=True
                    ),
                ),
                (
                    "mobile",
                    models.IntegerField(
                        blank=True, help_text="patient phone number?", null=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("occupation", models.CharField(max_length=500)),
                ("employers_numbers", models.IntegerField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("hausa", "Hausa"),
                            ("pigin", "Pigin"),
                            ("french", "French"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("caucacian", "Caucacian"),
                            ("asian", "Asian"),
                            ("hispanic", "Hispanic"),
                        ],
                        max_length=500,
                    ),
                ),
                (
                    "homeless",
                    models.BooleanField(blank=True, help_text="optional*", null=True),
                ),
            ],
        ),
    ]
