# Generated by Django 4.1.5 on 2023-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(),
        ),
    ]
