# Generated by Django 4.2.7 on 2023-11-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_user_pic"),
        ("patient", "0002_alter_patient_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_category",
                    models.CharField(
                        choices=[
                            ("established patient", "Established Patient"),
                            ("new patient", "New Patient"),
                            ("office visit", "Office Visit"),
                            ("reserved", "Reserved"),
                        ],
                        max_length=300,
                    ),
                ),
                ("date_of_service", models.DateField(auto_now=True, null=True)),
                (
                    "type_title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("problem", "Problem"),
                            ("allergy", "Allergy"),
                            ("medication", "Medication"),
                            ("surgery", "Surgery"),
                            ("dental", "Dental"),
                        ],
                        help_text="select one of these type title",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("begin_date", models.DateField(auto_now=True)),
                (
                    "end_date",
                    models.DateField(
                        auto_now=True,
                        help_text="leave blank if still active",
                        null=True,
                    ),
                ),
                ("diagnosis", models.TextField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("unassigned", "Unassigned"),
                            ("resolved", "Resolved"),
                            ("improved", "Improved"),
                            ("status quo", "Status quo"),
                            ("worse", "Worse"),
                            ("pending followup", "Pending followup"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.facility",
                    ),
                ),
            ],
        ),
    ]
