# Generated by Django 4.2.7 on 2023-11-15 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_rename_type_title_visit_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="begin_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="date_of_service",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="leave blank if still active",
                null=True,
            ),
        ),
    ]
