# Generated by Django 4.2.7 on 2023-11-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_alter_visit_begin_date_alter_visit_date_of_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unassigned", "Unassigned"),
                    ("resolved", "Resolved"),
                    ("improved", "Improved"),
                    ("status quo", "Status quo"),
                    ("worse", "Worse"),
                    ("pending followup", "Pending followup"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
