# Generated by Django 4.2.7 on 2023-11-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0009_visit_provider_alter_visit_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_in_lbs", models.FloatField(blank=True, null=True)),
                ("weight_in_kg", models.FloatField(blank=True, null=True)),
                ("height_in_cm", models.FloatField(blank=True, null=True)),
                ("BP_systolic_mmkg", models.FloatField(blank=True, null=True)),
                ("BP_diastolic_mmkg", models.FloatField(blank=True, null=True)),
                ("pulse_per_min", models.FloatField(blank=True, null=True)),
                ("respiration_per_min", models.FloatField(blank=True, null=True)),
                ("temperature_f", models.FloatField(blank=True, null=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                (
                    "temp_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("oral", "Oral"),
                            ("tympanic membrane", "Tympanic Membrane"),
                            ("rectal", "Rectal"),
                            ("auxillary", "Auxillary"),
                            ("temporal artery", "Temporal Artery"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "oxygen_saturation_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("head_circumference_cm", models.FloatField(blank=True, null=True)),
                ("waist_circumference_cm", models.FloatField(blank=True, null=True)),
                ("BMI_kg_per_m2", models.FloatField(blank=True, null=True)),
                (
                    "BMI_status_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_notes",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patient.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjective", models.TextField(blank=True, null=True)),
                ("objective", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patient.visit"
                    ),
                ),
            ],
        ),
    ]
