# Generated by Django 4.1.5 on 2023-11-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0010_alter_visit_provider_vitals_soap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soap",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soap",
                to="patient.visit",
            ),
        ),
        migrations.AlterField(
            model_name="vitals",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vital",
                to="patient.visit",
            ),
        ),
    ]
