# Generated by Django 4.2.7 on 2023-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0015_alter_prescription_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("zip_code", models.IntegerField()),
                ("Phone", models.IntegerField()),
            ],
        ),
    ]
