# Generated by Django 4.2.7 on 2023-11-22 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0017_patient_insurance_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="naira")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "check_or_reference_number",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "posting_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patient.visit"
                    ),
                ),
            ],
        ),
    ]
