# Generated by Django 4.2.7 on 2023-11-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0018_checkout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visit",
            options={"verbose_name": "Encouter"},
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="patient.insurancecompany",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="patient.patient",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit",
                to="patient.patient",
            ),
        ),
    ]
