# Generated by Django 4.2.7 on 2023-11-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient",
            "0019_alter_visit_options_alter_patient_insurance_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout",
                to="patient.visit",
            ),
        ),
    ]
