# Generated by Django 4.2.7 on 2023-11-15 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calender", "0004_calender_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="calender",
            name="comments",
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="calender",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
