# Generated by Django 4.2.7 on 2023-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0005_calender_comments_alter_calender_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calender",
            old_name="user",
            new_name="provider",
        ),
        migrations.AlterField(
            model_name="calender",
            name="comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
