# Generated by Django 4.2.7 on 2023-11-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0011_alter_soap_encounter_alter_vitals_encounter"),
        ("calender", "0007_alter_calender_date_alter_calender_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calender",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
    ]
