# Generated by Django 4.2.7 on 2023-11-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0011_alter_soap_encounter_alter_vitals_encounter"),
        ("calender", "0008_calender_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="calender",
            name="room_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("room 1", "Room 1"),
                    ("room 2", "Room 2"),
                    ("room 3", "Room 3"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="calender",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
    ]
