# Generated by Django 4.2.7 on 2023-11-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0009_calender_room_number_alter_calender_patient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calender",
            options={"verbose_name": "Appointment"},
        ),
    ]
